// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class Articles
    {
        public string ArticleId { get; set; }
        public string UserId { get; set; }
        public string ClassId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}