// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class ArticleTagsDetail
    {
        public string ArticleId { get; set; }
        public string TagId { get; set; }
    }
}