// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class ClassAll
    {
        public string UserId { get; set; }
        public string ClassId { get; set; }
        public string ClassName { get; set; }
    }
}