// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class ForgotPwdRecords
    {
        public string UserEmail { get; set; }
        public string Token { get; set; }
        public int? TokenTimeout { get; set; }
        public DateTime? SendTime { get; set; }
    }
}