// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class LoginRecords
    {
        public string UserId { get; set; }
        public DateTime LoginTime { get; set; }
        public string LoginState { get; set; }
    }
}