// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DBClassLibrary
{
    public partial class Members
    {
        //[DisplayName("帳號")]
        //[Required(ErrorMessage = "請輸入帳號")]
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        //[DisplayName("密碼")]
        //[DataType(DataType.Password)]
        //[Required(ErrorMessage = "請輸入密碼")]
        public string UserPwd { get; set; }
        public string RoleId { get; set; }
        public bool? IsEmailValid { get; set; }
        public bool? IsThirdLogin { get; set; }
    }
}