// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class Roles
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public string Platform { get; set; }
        public bool? CanQuery { get; set; }
        public bool? CanUpdate { get; set; }
    }
}