// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class Tags
    {
        public string UserId { get; set; }
        public string TagId { get; set; }
        public string TagName { get; set; }
    }
}