// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace DBClassLibrary
{
    public partial class UserIntroduction
    {
        public string UserId { get; set; }
        public string Introduction { get; set; }
        public string Photo { get; set; }
        public string LocalPath { get; set; }
    }
}